Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PNT1_Grupo6.Context;
using PNT1_Grupo6.Models;

namespace PNT1_Grupo6.Controllers
{
    public class ProductosController : Controller
    {
        private readonly GestorDatabaseContext _context;

        public ProductosController(GestorDatabaseContext context)
        {
            _context = context;
        }

        // GET: Productos
        public async Task<IActionResult> Index(string orderBy)
        {
            var productos = await _context.Productos.ToListAsync();

            // Aplicar ordenamiento si se especifica
            if (!string.IsNullOrEmpty(orderBy))
            {
                switch (orderBy)
                {
                    case "Id":
                        productos = productos.OrderBy(p => p.Id).ToList();
                        break;
                    case "Nombre":
                        productos = productos.OrderBy(p => p.Nombre).ToList();
                        break;
                    case "MayorPrecio":
                        productos = productos.OrderByDescending(o => o.PrecioVenta).ToList();
                        break;
                    case "MenorPrecio":
                        productos = productos.OrderBy(o => o.PrecioVenta).ToList();
                        break;
                }
            }

            return View(productos);
        }

        // GET: Productos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

        // GET: Productos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Productos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Stock,MaximoAlmacenable,Descripcion,PrecioVenta")] Producto producto)
        {
            if (ModelState.IsValid && ValidateData(producto))
            {
                _context.Add(producto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return RedirectToAction(nameof(Index));
            }
            //return View(producto);
        }

        // GET: Productos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos.FindAsync(id);
            if (producto == null)
            {
                return NotFound();
            }
            return View(producto);
        }

        // POST: Productos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Stock,MaximoAlmacenable,Descripcion,PrecioVenta")] Producto producto)
        {
            if (id != producto.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (!ValidateStockAndPricing(producto))
                {
                    return View(producto);
                }
                try
                {
                    _context.Update(producto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductoExists(producto.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(producto);
        }

        // GET: Productos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

        // POST: Productos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var producto = await _context.Productos.FindAsync(id);
            _context.Productos.Remove(producto);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductoExists(int id)
        {
            return _context.Productos.Any(e => e.Id == id);
        }

        private bool ValidateStockAndPricing(Producto producto)
        {
            bool isValid = true;
            if (producto.PrecioVenta <= 0)
            {
                TempData["ProductoError"] = "Fije un precio positivo!.";
                isValid = false;
            }
            else if (producto.Stock > producto.MaximoAlmacenable || producto.Stock < 0 || producto.MaximoAlmacenable <= 0)
            {
                TempData["ProductoError"] = "El stock no puede ser nulo o mayor al máximo almacenable.";
                isValid = false;
            }
            return isValid;
        }
        private bool ValidateData(Producto producto)
        {
            bool isValid = true;
            if (ProductoExists(producto.Id))
            {
                TempData["ProductoError"] = "El producto: " + producto.Id + " ya se encuentra registrado.";
                isValid = false;
            }
            else if (!ValidateStockAndPricing(producto))
            {
                isValid = false;
            }

            return isValid;
        }
    }
}

Controllers/SessionsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using PNT1_Grupo6.Models;
using PNT1_Grupo6.Context;

namespace PNT1_Grupo6.Controllers
{
    public class SessionsController : Controller
    {
        private readonly GestorDatabaseContext _context;

        public SessionsController(GestorDatabaseContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            // Si las variables de sesión ya están asignadas, redirige al dashboard
            if (HttpContext.Session.GetString("Rol") != null && HttpContext.Session.GetString("UserName") != null)
            {
                return RedirectToAction("Dashboard");
            }
            else
            {
                return View();
            }
        }

        [HttpPost]
        public IActionResult Login(string username, string password)
        {
            // Si ya hay variables de usuario porque ya nos logeamos, no debería ir al login
            if (HttpContext.Session.GetString("Rol") != null && HttpContext.Session.GetString("UserName") != null)
            {
                return RedirectToAction("Dashboard");
            }
            // Validar el usuario y contraseña en la base de datos
            var user = _context.Usuarios.FirstOrDefault(u => u.UserName == username && u.Password == password);

            if (user != null)
            {
                // Guardar el rol del usuario en la variable de sesión
                HttpContext.Session.SetString("Rol", user.RolUsuario.ToString());
                HttpContext.Session.SetString("UserName", user.Nombre.ToString());

                HttpContext.Session.SetObject("Usuario", user);

                ViewData["Usuario"] = user;
                return RedirectToAction("Dashboard");
            }
            else
            {
                TempData["LoginError"] = "Credenciales inválidas";
                Usuario invalidUser = new Usuario { Nombre = username };
                return RedirectToAction(nameof(Index));
            }
        }

        public IActionResult Dashboard()
        {
            var usuario = HttpContext.Session.GetObject<Usuario>("Usuario");

            if (usuario != null)
            {
                ViewData["Usuario"] = usuario;
                return View(usuario);
            }
            else
            {
                // El usuario no existe o no ha iniciado sesión correctamente
                TempData["LoginError"] = "No se ha iniciado sesión correctamente.";
                return RedirectToAction("Index");
            }
        }

        public IActionResult Logout()
        {
            // Eliminar las variables de sesión
            HttpContext.Session.Remove("Rol");
            HttpContext.Session.Remove("UserName");
            HttpContext.Session.Remove("Usuario");

            return RedirectToAction("Index", "Home"); // Redirigir a la página de inicio u otra página de tu elección
        }

        // GET: Sessions/CreateNewUser
        public IActionResult CreateNewUser()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Usuario usuario)
        {
            if (ModelState.IsValid && (!DniExists(usuario.Dni) && !UserNameExists(usuario.UserName)))
            {
                _context.Add(usuario);
                await _context.SaveChangesAsync();

                // Guardar el rol del usuario en la variable de sesión
                HttpContext.Session.SetString("Rol", usuario.RolUsuario.ToString());
                HttpContext.Session.SetString("UserName", usuario.UserName.ToString());
                // Guardar el objeto usuario en la sesión
                HttpContext.Session.SetObject("Usuario", usuario);

                // Redirigir al dashboard
                return RedirectToAction("Dashboard");
            }
            else
            {
                TempData["CreateNewUserError"] = "No se pudo crear el usuario debido a duplicados. Usuario y/o dni ya existentes.";
                return RedirectToAction("CreateNewUser");
            }

        }

        private bool DniExists(int dni)
        {
            bool exists = _context.Usuarios.Any(e => e.Dni == dni);
            if (exists)
            {
                TempData["CreateNewUserError"] = "Dni repetido.";
            }
            return exists;
        }
        private bool UserNameExists(string user)
        {
            bool exists = _context.Usuarios.Any(e => e.UserName == user);
            if (exists)
            {
                TempData["CreateNewUserError"] = "Usuario repetido.";
            }
            return exists;
        }
    }
}

Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PNT1_Grupo6.Context;
using PNT1_Grupo6.Models;

namespace PNT1_Grupo6.Controllers
{
    public class UsuariosController : Controller
    {
        private readonly GestorDatabaseContext _context;

        public UsuariosController(GestorDatabaseContext context)
        {
            _context = context;
        }

        // GET: Usuarios
        [AuthorizeRole(Rol.Admin)]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Usuarios.ToListAsync());
        }

        // GET: Usuarios/Details/5
        [AuthorizeRole(Rol.Admin)]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // GET: Usuarios/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Usuarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserName,Nombre,Apellido,Dni,Password,RolUsuario")] Usuario usuario)
        {
            if (ModelState.IsValid && (!DniExists(usuario.Dni) && !UserNameExists(usuario.UserName)))
            {
                _context.Add(usuario);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            else
            {
                return RedirectToAction(nameof(Index));
            }
            //return View(usuario);
        }

        // GET: Usuarios/Edit/5
        [AuthorizeRole(Rol.Admin)]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios.FindAsync(id);
            if (usuario == null)
            {
                return NotFound();
            }
            return View(usuario);
        }

        // POST: Usuarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeRole(Rol.Admin)]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserName,Nombre,Apellido,Dni,Password,RolUsuario")] Usuario usuario)
        {
            if (id != usuario.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if(UserNameExists(usuario.UserName))
                {
                    return RedirectToAction(nameof(Index));
                }

                try
                {
                    _context.Update(usuario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsuarioExists(usuario.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(usuario);
        }

        // GET: Usuarios/Delete/5
        [AuthorizeRole(Rol.Admin)]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // POST: Usuarios/Delete/5
        [AuthorizeRole(Rol.Admin)]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var usuario = await _context.Usuarios.FindAsync(id);
            _context.Usuarios.Remove(usuario);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UsuarioExists(int id)
        {
            return _context.Usuarios.Any(e => e.Id == id);
        }

        private bool DniExists(int dni)
        {
            bool exists = _context.Usuarios.Any(e => e.Dni == dni);
            if (exists)
            {
                TempData["UsuariosError"] = "Dni repetido.";
            }
            return exists;
        }
        private bool UserNameExists(string user)
        {
            bool exists = _context.Usuarios.Any(e => e.UserName == user);
            if (exists)
            {
                TempData["UsuariosError"] = "Usuario repetido.";
            }
            return exists;
        }
    }
}

Views/Shared/_Layout.cshtml
@{
    var usuario = Context.Items["Usuario"] as Usuario;

}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PNT1_Grupo6</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="container layout-container">
    <header>
        <nav class=" navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-color border-bottom box-shadow mb-3 dark-color">
            <div class="container">
                <a class="navbar-brand no-burbujas ml-0 font-size-20" asp-area="" asp-controller="Home" asp-action="Index">Gestor de Productos</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="lista navbar-nav flex-grow-1">
                        @{
                            //var usuario = ViewData["Usuario"] as Usuario;
                        }
                        @if (usuario != null)
                        {
                            <li class="burbujas nav-item">
                                <a class="nav-link text-dark amarillo" asp-area="" asp-controller="Usuarios" asp-action="Index">Usuarios</a>
                            </li>
                            <li class="burbujas nav-item naranja-claro">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Proveedores" asp-action="Index">Proveedores</a>
                            </li>
                            <li class="burbujas nav-item naranja-medio">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Productos" asp-action="Index">Productos</a>
                            </li>
                            <li class="burbujas nav-item naranja-oscuro">
                                <a class="nav-link text-dark" asp-area="" asp-controller="OrdenesCompra" asp-action="Index">Órdenes de compra</a>
                            </li>



                         <div class="derecha">
                            <li class=" nav-item">
                                <form asp-controller="Sessions" asp-action="Logout" method="post">
                                    <button type="submit" class="btn btn-sm text-dark sesion btn-cerrar-sesion ">Cerrar sesión</button>
                                </form>
                            </li>

                            <li class="avatar nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Sessions" asp-action="Index">
                                    <div class="d-flex align-items-center">
                                        <div class="ml-2">
                                            <div class="font-weight-bold">@usuario.UserName</div>
                                            <div class="small text-muted">@usuario.RolUsuario</div>
                                        </div>
                                        <div class="avatar-image">
                                            <!-- Agregar imagen del avatar circular aquí -->
                                            <img src="~/css/user-icon.png" alt="Avatar" class="avatar-image" />
                                        </div>
                                    </div>
                                </a>
                            </li>
                         </div>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Sessions" asp-action="Index">Iniciar sesión</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Gestor de producros - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

<style>
    .avatar{
        
        background-color:orange;
        border-radius:25px;
    }
    .avatar-image{
        color:red;
        
    }
    .dark-color {
        background-color: #F5F5DC;
    }

    .azul{
        background-color:blue;
    }
    .derecha{
        display:flex;
        margin-left:280px;

    }
    
    .sesion:hover{
        text-decoration:underline;
        
    }
    .burbujas {
        
        border-radius: 20px;
        text-align: center;
        max-width: 200px;
        height: 50px;
        margin: 10px;
        overflow: hidden;
        white-space: nowrap;
        text-overflow: ellipsis;
    }

        .burbujas a {
            font-weight: bold;
            line-height: 2;
        }

    .navbar-brand {
        background-color: indianred;
        border: 2px solid #000;
        border-radius: 0;
        padding: 10px 20px;
        display: inline-block;
        color: #000;
        text-decoration: none;
        font-size: 18px;
    }

    .sesion {
        background-color: red;
        border: none;
        border-radius: 20px;
        padding: 5px 10px;
        color: white;
        font-size: 14px;
        white-space: nowrap;
    }

    .font-size-20 {
        font-size: 20px;
        margin-right:150px;
    }

    .amarillo {
        background-color: #FFD700; /* Amarillo */
    }

    .naranja-claro {
        background-color: #FFA500; /* Naranja claro */
    }

    .naranja-medio {
        background-color: #FF8C00; /* Naranja medio */
    }

    .naranja-oscuro {
        background-color: #FF4500; /* Naranja oscuro */
    }
</style>