Controllers/ProveedoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PNT1_Grupo6.Context;
using PNT1_Grupo6.Models;

namespace PNT1_Grupo6.Controllers
{
    public class ProveedoresController : Controller
    {
        private readonly GestorDatabaseContext _context;

        public ProveedoresController(GestorDatabaseContext context)
        {
            _context = context;
        }

        // GET: Proveedores
        public async Task<IActionResult> Index()
        {
            return View(await _context.Proveedores.ToListAsync());
        }

        // GET: Proveedores/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var proveedor = await _context.Proveedores
                .FirstOrDefaultAsync(m => m.Id == id);
            if (proveedor == null)
            {
                return NotFound();
            }

            return View(proveedor);
        }

        // GET: Proveedores/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Proveedores/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Email,Telefono,Rubro")] Proveedor proveedor)
        {
            if (ModelState.IsValid && ValidateData(proveedor.Id, proveedor.Email))
            {
                _context.Add(proveedor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return RedirectToAction(nameof(Index));
            }
            //return View(proveedor);
        }

        // GET: Proveedores/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var proveedor = await _context.Proveedores.FindAsync(id);
            if (proveedor == null)
            {
                return NotFound();
            }
            return View(proveedor);
        }

        // POST: Proveedores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Email,Telefono,Rubro")] Proveedor proveedor)
        {
            if (id != proveedor.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (!ValidEmail(proveedor.Email))
                {
                    TempData["ProveedorError"] = "El email provisto no cumple con el formato esperado.";
                    return View(proveedor);
                }
                try
                {
                    _context.Update(proveedor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProveedorExists(proveedor.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(proveedor);
        }

        // GET: Proveedores/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var proveedor = await _context.Proveedores
                .FirstOrDefaultAsync(m => m.Id == id);
            if (proveedor == null)
            {
                return NotFound();
            }

            return View(proveedor);
        }

        // POST: Proveedores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var proveedor = await _context.Proveedores.FindAsync(id);
            _context.Proveedores.Remove(proveedor);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // POST: Proveedores/BuscarPorNombre?q=
        public async Task<IActionResult> BuscarPorNombre(string q)
        {
            /*string query1 = "SELECT * FROM Proveedores WHERE 'Nombre' LIKE '%'" + q + "'%'";*/
            try
			{
                var resultados = await _context.Proveedores.Where(e => e.Nombre.ToLower().Contains(q.ToLower()))
            .ToListAsync();
                var viewModel = new BuscarProveedoresViewModel { Proveedores = resultados };
                return View(viewModel);

            } catch (Exception e)
			{
                return NotFound();
            }
             
        }

        private bool ProveedorExists(int id)
        {
            return _context.Proveedores.Any(e => e.Id == id);
        }

        private bool ValidateData(int code, string email)
        {
            bool state = false;
            if (ProveedorExists(code))
            {
                TempData["ProveedorError"] = "El proveedor con código: " + code + " ya se encuentra registrado.";
            }
            else if (!ValidEmail(email))
            {
                TempData["ProveedorError"] = "El email provisto no cumple con el formato esperado.";
            }
            else
            {
                state = true;
            }
            return state;
        }

        private bool ValidEmail(string email)
        {
            // Expresión regular para validar direcciones de correo electrónico
            string pattern = @"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$";

            // Comprobar si el correo electrónico coincide con el patrón
            Match match = Regex.Match(email, pattern);

            return match.Success;
        }
    }
}

Views/Proveedores/BuscarPorNombre.cshtml
@model BuscarProveedoresViewModel

@{
    ViewData["Title"] = "ResultadosBusqueda";
}
<table>
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Descripción</th>
            <!-- Agrega más columnas según tus necesidades -->
        </tr>
    </thead>
    <tbody>
        @foreach (var proveedor in Model.Proveedores)
        {
            <tr>
                <td>@proveedor.Nombre</td>
                <td>@proveedor.Email</td>
                <!-- Agrega más celdas según tus necesidades -->
            </tr>
        }
    </tbody>
</table>

<div>
    <a class="rojo" asp-action="Index">Volver a la lista</a>
</div>

Views/Proveedores/Create.cshtml
@model PNT1_Grupo6.Models.Proveedor

@{
    ViewData["Title"] = "Create";
}

<div class="fondo">
    <h1>Create</h1>

    <h4>Proveedor</h4>
</div>
<hr />
<div class="cont">
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Nombre" class="control-label"></label>
                    <input asp-for="Nombre" class="form-control" />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Email" class="control-label"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Telefono" class="control-label"></label>
                    <input asp-for="Telefono" class="form-control" />
                    <span asp-validation-for="Telefono" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Rubro" class="control-label"></label>
                    <input asp-for="Rubro" class="form-control" />
                    <span asp-validation-for="Rubro" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Crear" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

    <div>
        <a class="rojo" asp-action="Index">Volver a la lista</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

    <style>
        .fondo {
            background-color: #1861ac;
            border-radius: 10px;
            color: white;
            text-align: center;
        }

        .cont {
            margin-left: 460px;
        }

        .rojo {
            padding: 8px 16px;
            background-color: red;
            color: white;
            text-decoration: none;
            border-radius: 5px;
        }

            .rojo:hover {
                background-color: darkred;
                color: white;
                text-decoration: none;
            }

        .btn {
            background-color: green;
        }

            .btn:hover {
                background-color: darkgreen;
            }
    </style>

Views/Proveedores/Delete.cshtml
@model PNT1_Grupo6.Models.Proveedor

@{
    ViewData["Title"] = "Delete";
}

<div class="fondo">
    <h1>Eliminar</h1>

    <h3>Estas seguro de que quieres eliminar esto?</h3>
</div>
<div>
    <h4>Proveedor</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rubro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rubro)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <div class="botones">
            <input type="submit" value="Eliminar" class="btn btn-danger" /> |
            <a class="verde" asp-action="Index">Volver a la lista</a>
        </div>
    </form>
</div>

<style>
    .row {
        margin-left: 430px;
    }

    .botones {
        margin-left: 430px;
    }

    .verde {
        padding: 8px 16px;
        background-color: green;
        color: white;
        text-decoration: none;
        border-radius: 5px;
    }

        .verde:hover {
            color: white;
            text-decoration: none;
            background-color: darkgreen;
        }

    .fondo {
        background-color: #1861ac;
        border-radius: 10px;
        color: white;
        text-align: center;
    }
</style>

Views/Proveedores/Details.cshtml
@model PNT1_Grupo6.Models.Proveedor

@{
    ViewData["Title"] = "Details";
}

<div class="fondo">
    <h1>Mas informacion</h1>
</div>

<div>
    <h4>Proveedor</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rubro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rubro)
        </dd>
    </dl>
</div>
<div class="botones">
    <a class="rojo" asp-action="Edit" asp-route-id="@Model.Id">Editar</a> |
    <a class="verde" asp-action="Index">Volver a la lista</a>
</div>

<style>
    .row {
        margin-left: 400px;
    }

    .botones {
        margin-left: 400px;
    }

    .rojo {
        padding: 8px 16px;
        background-color: red;
        color: white;
        text-decoration: none;
        border-radius: 5px;
    }

        .rojo:hover {
            color: white;
            text-decoration: none;
            background-color: darkred;
        }

    .verde {
        padding: 8px 16px;
        background-color: green;
        color: white;
        text-decoration: none;
        border-radius: 5px;
    }

        .verde:hover {
            color: white;
            text-decoration: none;
            background-color: darkgreen;
        }

    .fondo {
        background-color: #1861ac;
        border-radius: 10px;
        color: white;
        text-align: center;
    }
</style>

Views/Proveedores/Edit.cshtml
@model PNT1_Grupo6.Models.Proveedor

@{
    ViewData["Title"] = "Edit";
}

<div class="fondo">
    <h1>Edit</h1>
    @if (TempData["ProveedorError"] != null)
    {
        <div class="alert alert-danger">
            @TempData["ProveedorError"]
        </div>}

    <h4>Proveedor</h4>
</div>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rubro" class="control-label"></label>
                <input asp-for="Rubro" class="form-control" />
                <span asp-validation-for="Rubro" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="verde btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="rojo" asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<style>
    h1, h4 {
        text-align: center;
    }

    .row {
        display: flex;
        justify-content: center;
    }

    .col-md-4 {
        text-align: center;
    }

    form {
        max-width: 400px;
    }

    .btn-submit {
        margin: 0 auto;
        display: block;
    }

    .verde {
        background-color: green;
        display: inline;
    }

        .verde:hover {
            background-color: darkgreen;
        }

    .rojo {
        padding: 8px 16px;
        background-color: red;
        color: white;
        text-decoration: none;
        border-radius: 5px;
    }

        .rojo:hover {
            color: white;
            text-decoration: none;
            background-color: darkred;
        }

    .fondo {
        background-color: #1861ac;
        border-radius: 10px;
        color: white;
    }
</style>

Views/Proveedores/Index.cshtml
@model IEnumerable<PNT1_Grupo6.Models.Proveedor>

@{
    ViewData["Title"] = "Index";
}

<h1>Proveedores</h1>
@if (TempData["ProveedorError"] != null)
{
    <div class="alert alert-danger">
        @TempData["ProveedorError"]
    </div>}
<p>
    <a class="btn-create" asp-action="Create">Crear nuevo</a>
</p>

<form action="@Url.Action("BuscarPorNombre", "Proveedores")" method="GET">
    <input type="text" name="q" placeholder="Buscar..." />
    <button type="submit">Buscar</button>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefono)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rubro)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Telefono)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rubro)
                </td>
                <td>
                    <a class="verde" asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                    <a class="amarillo" asp-action="Details" asp-route-id="@item.Id">Info</a> |
                    <a class="rojo" asp-action="Delete" asp-route-id="@item.Id">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<style>
    .fondo-tabla {
        background-color: darkgray;
        border: 3px solid black;
    }

    .blanco {
        color: white;
    }

    .btn-create {
        display: inline;
        padding: 8px 16px;
        background-color: green;
        color: white;
        text-decoration: none;
        border-radius: 5px;
        margin-left: 300px;
    }

        .btn-create:hover {
            color: black;
            text-decoration: none;
        }

    h1 {
        display: inline;
    }

    .verde {
        padding: 8px 16px;
        background-color: green;
        color: black;
        text-decoration: none;
        border-radius: 15px;
    }

    .amarillo {
        padding: 8px 16px;
        background-color: yellow;
        color: black;
        text-decoration: none;
        border-radius: 15px;
    }

    .rojo {
        padding: 8px 16px;
        background-color: red;
        color: black;
        text-decoration: none;
        border-radius: 15px;
    }
    .table{
        border:3px solid black;
    }
</style>